### ISSUE TITLE
Identify Which Variants correspond to PM1

### ISSUE THREAD

**Issue by giphahne** [genewhisper/genewhisper#1]
http://portals.broadinstitute.org/oncotator/help/

**Comment by seaspray09** [comment]
Identify which variants correspond to PM1

from Oncotator exampleoutput.tsv, look at "UniProt Region" and "Variant Classification" columns

if (UniProt Region has some entry AND Variant Classification = Missense)
then PM1 = true

This may be done by adding a column "PM1" to the same table "exampleoutput.tsv"

**Comment by giphahne** [comment]
so, it sounds like this script should take _a row of the exampleOutput.tsv_ file.

**Comment by giphahne** [comment]
PM1 criteria are here: http://www.medschool.umaryland.edu/Genetic_Variant_Interpretation_Tool1.html/
