### ISSUE TITLE
Please read and sign NDA!  

### ISSUE THREAD

**Issue by kennethto** [genewhisper/genewhisper#10]
This document is required from everyone before we  can move forward!!
Please read, sign and date (put 9/1/2017) with the attached NDA, then upload it back to this ticket before 1/12/2018. 
[Confidentiality and NDA.pdf](https://github.com/genewhisper/genewhisper/files/1602056/Confidentiality.and.NDA.pdf)

**Comment by aagraw16** [comment]
Hi Ken.
Please find attached the signed NDA.
[Confidentiality.and.NDA_Ayushi.pdf](https://github.com/genewhisper/genewhisper/files/1601927/Confidentiality.and.NDA_Ayushi.pdf)

**Comment by kennethto** [comment]
Ayushi, can you please resign the newly uploaded NDA please.. sorry for the confusion

**Comment by seaspray09** [comment]
Here is my signed NDA

[Confidentiality.and.NDA_Anwar Husain.pdf](https://github.com/genewhisper/genewhisper/files/1602721/Confidentiality.and.NDA_Anwar.Husain.pdf)

**Comment by aagraw16** [comment]
Hi Ken. 
Please find attached the signed NDA.
[ConfidentialityandNDA-Ayushi.pdf](https://github.com/genewhisper/genewhisper/files/1604039/ConfidentialityandNDA-Ayushi.pdf)

**Comment by giphahne** [comment]
NDA attached: 
[Confidentiality_and_NDA_dan-hahne.pdf](https://github.com/genewhisper/genewhisper/files/1607066/Confidentiality_and_NDA_dan-hahne.pdf)

**Comment by jasonachonu** [comment]
Hi Ken.
Please find attached the signed NDA
[Confidentiality.and.NDA_Jason_Achonu.pdf](https://github.com/genewhisper/genewhisper/files/1624190/Confidentiality.and.NDA_Jason_Achonu.pdf)
