### ISSUE TITLE
BA1 Allele frequency is >5% in Exome Sequencing Project, 1000 Genomes Project, or Exome Aggregation Consortium

### ISSUE THREAD

**Issue by kennethto** [genewhisper/genewhisper#11]
Apply BA1 if one of the following is disease causing
ExAC_AF: anything > OR = 5% is "True" for BA1;
or
1000gp3_AF: anything > OR = 5% is "True" for BA1

**Comment by mzhakun** [comment]
What should be the output if the field is empty?

**Comment by kennethto** [comment]
This would be similar to PM2. I believe it was to assign "False" if it is empty? please check.

**Comment by mzhakun** [comment]
No,  it was actually True
I'm changing BA1 return true if the field is empty, @kennethto, please confirm?

**Comment by kennethto** [comment]
Thinking about this a little more, it should be "TBD" if it empty, not true for BA1. Please make the edit. Thanks
