### ISSUE TITLE
Review oncotator output "Variant_Classification" column I and "Ensembl_so_term" column DU

### ISSUE THREAD

**Issue by kennethto** [genewhisper/genewhisper#15]
1) need to figure out and research ALL possible output in column I "Variant_Classification" and "Ensembl_so_term" column DU. please list them here in this ticket. 

2) This information can be used to assign ACMG criteria possible, in which separate tickets will be submited

Ask me if you have any questions

**Comment by mzhakun** [comment]
Ken, generally, the variant classifications are derived from TCGA MAF. https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+(MAF)+Specification#MutationAnnotationFormat(MAF)Specification-MAFfilechecks

"Intron" -- variant lies between exons within the bounds of the chosen transcript.
"5'UTR" -- variant is on the 5'UTR for the chosen transcript
"3'UTR" -- variant is on the 3'UTR for the chosen transcript
"IGR" -- intergenic region. Does not overlap any transcript.
"5'Flank" -- the variant is upstream of the chosen transcript (within 3kb)
"Missense_Mutation" -- the point mutation alters the protein structure by one amino acid. https://en.wikipedia.org/wiki/Missense_mutation
"Nonsense_Mutation" -- a premature stop codon is created by the variant. https://en.wikipedia.org/wiki/Nonsense_mutation
"Nonstop_Mutation" -- variant removes stop codon.
"Silent" -- variant is in coding region of the chosen transcript, but protein structure is identical. I.e. a synonymous mutation
"Splice_Site" -- the variant is within two bases of a splice site. See the secondary classification to determine if it lies on the exon or intron side.
"In_Frame_Del" -- deletion that keeps the sequence in frame
"In_Frame_Ins" -- insertion that keeps the sequence in frame
"Frame_Shift_Ins" -- insertion that moves the coding sequence out of frame (https://en.wikipedia.org/wiki/Frameshift_mutation)
"Frame_Shift_Del" -- deletion that moves the coding sequence out of frame (https://en.wikipedia.org/wiki/Frameshift_mutation)
"Start_Codon_SNP" -- point mutation that overlaps the start codon.
"Start_Codon_Ins" -- insertion that overlaps the start codon.
"Start_Codon_Del" -- seletion that overlaps the start codon.
"De_novo_Start_InFrame" -- New start codon is created by the given variant using the chosen transcript. However, it is in frame relative to the coded protein.
"De_novo_Start_OutOfFrame" -- New start codon is created by the given variant using the chosen transcript. However, it is out of frame relative to the coded protein.
"RNA" -- variant lies on one of the RNA transcripts.
"lincRNA" -- variant lies on one of the lincRNAs.
The secondary classification is when there is ambiguity in the primary variant classification. For example, when the primary classification is "Splice_Site". The secondary classification will have more information, such as whether the variant was on the intron side of the splice site.

**Comment by kennethto** [comment]
I know all these terms but I just want to make sure both "Variant_Classification" and "Ensembl_so_term" are using the exact same term as listed above? Please confirm

**Comment by seaspray09** [comment]
Yes, it appears that "Variant Classification" and  "Ensembl_SO_term" would be synonymous.

For each variant that is mapped to the reference genome,  there are Ensembl transcripts that overlap the variant. A rule-based approach is then used to predict the effects that each allele of the variant may have on the transcript. The set of consequence terms is defined by the Sequence Ontology (SO).  These terms are assigned to each combination of an allele and a transcript (see the link below). Each allele of each variant however may have a different effect in different transcripts.  This approach is applied to all germline variants and somatic mutations stored in the Ensembl variation databases.

https://useast.ensembl.org/info/genome/variation/predicted_data.html
