### ISSUE TITLE
ACMG 2015 Table 5 Rules for combining criteria to classify sequence variants

### ISSUE THREAD

**Issue by kennethto** [genewhisper/genewhisper#9]
https://www.acmg.net/docs/Standards_Guidelines_for_the_Interpretation_of_Sequence_Variants.pdf

Someone please work on this independently. The script should be working independently disregard to what criteria are assign to a given variant

**Comment by kennethto** [comment]
@mzhakun I believe you are already working on this and almost done? just checking

**Comment by mzhakun** [comment]
@kennethto, It's all complete. Dean will do some cleanup, that's all.

**Comment by kennethto** [comment]
@mzhakun , what is the default classification if it doesn't meet any rules on the table?
